# Generated by Django 3.1.7 on 2022-01-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220107_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='proof',
        ),
    ]
